# Base image
FROM python:3.10

# Copy all files from current directory to container
COPY . .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Command to run FastAPI
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "7860"]
